on:
  pull_request:
    branches:
      - candle-addition-springyworks-16aug2025
      - main

name: Secret Leaks

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      env:
        # Pass ignore file to action
        ARGS: "--exclude-paths .trufflehogignore"
